application:
  name: dnstoolkit
  version: 1.0.0
  description: DNS Toolkit
dns_toolkit:
  folders:
    download: data/download
    processed: data/processed
    consolidated: data/consolidated
    summary: data
  source_files:
    - data/config/sources_domain_bl.json
    - data/config/sources_domain_al.json
    - data/config/sources_local.json
    - data/config/sources_ip.json
    - data/config/sources_mis.json
  files_checksum:
    enabled: true
    algorithm: "md5" # md5, sha256
multilog:
  handlers:
    - type: console
      level: perf
      enabled: true
      use_single_letter_level: true
      pattern: "[[time]]-[[level]] [msg]"
    - type: file
      subtype: text
      level: debug
      enabled: true
      pattern: "[date] - [[time]] [[level]] [[source]] [msg]"
      file: logs/dns-toolkit.log
      max_size: 5 # MB
      max_backups: 7
      max_age: 1 # days
