application:
  name: dns-toolkit
  version: 0.1.0
  description: A toolkit for DNS data processing and analysis.
dns_toolkit:
  folders:
    download: data/download
    processed: data/processed
    consolidated: data/consolidated
    summary: data
    top: data/top
    consolidated_groups: data/consolidated_groups
    consolidated_categories: data/consolidated_categories
    archive: data/archive
    output: data/output
    backup: data/backup
    profiles: data/profiles
  source_files:
    - data/config/sources_domain_bl.json
    - data/config/sources_domain_al.json
    - data/config/sources_local.json
    - data/config/sources_ip.json
    - data/config/sources_domain_top.json
    - data/config/sources_domain_new.json
    - data/config/sources_mis.json
  files_checksum:
    enabled: true
    algorithm: "md5" # md5, sha256
  skip_unchanged_downloads: true
  skip_name_special_chars_check: true
  skip_cert_verification: true
  skip_cert_verification_hosts:
    - "raw.githubusercontent.com"
    - "tranco-list.eu"
    - "github.com"
  max_workers: 1
  max_retries: 3
  source_filters:
    name:
      contains:
        #- "Local"
multilog:
  handlers:
    - type: console
      level: perf
      enabled: true
      use_single_letter_level: true
      pattern: "[[time]]-[[level]] [msg]"
    - type: file
      subtype: text
      level: debug
      enabled: true
      pattern: "[date] - [[time]] [[level]] [[source]] [msg]"
      file: logs/dns-toolkit.log
      max_size: 5 # MB
      max_backups: 7
      max_age: 1 # days
